<a href="https://colab.research.google.com/github/plee0617/IS-170-Binder/blob/Naive-Bayes/LeeIS170_Lab8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Pang Yia Lee
3/29/2023

Students will get extra credits/points on their exam if they got question #5 (the hardest question) correct, and they scored at least 70% or higher.

In [ ]:
import pandas as pd
import numpy as np

df=pd.read_csv("Extracredit.csv")
df

Question #5 More than 70% Extra Credit
0           No           Yes           No
1          Yes            No           No
2           No            No           No
3           No            No           No
4          Yes           Yes          Yes
5           No            No           No
6           No            No           No
7           No           Yes           No
8          Yes           Yes          Yes
9          Yes           Yes          Yes
10         Yes           Yes          Yes
11         Yes           Yes          Yes
12          No           Yes           No
13         Yes           Yes          Yes
14         Yes           Yes          Yes
15         Yes            No           No

In [ ]:
#In order to process we must turn those categorical values into numberic values
#Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

#Using .fit_transform function to fit label
#encoder and return encoded label
question_label=le.fit_transform(df['Question #5'])

#printinglabel
question_label

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [ ]:
percent_label=le.fit_transform(df['More than 70%'])

percent_label

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
credit_label=le.fit_transform(df['Extra Credit'])

credit_label

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
#we'll use zip method in this function called merge to combine the two labels: Question5 and Percent
def merge (list1, list2):
  merged_list=tuple(zip(list1, list2))
  return merged_list

features=merge(question_label, percent_label)
features


((0, 1),
 (1, 0),
 (0, 0),
 (0, 0),
 (1, 1),
 (0, 0),
 (0, 0),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (1, 1),
 (0, 1),
 (1, 1),
 (1, 1),
 (1, 0))

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets
model.fit(features,credit_label)

#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print ("Predicted Value:", predicted)

Predicted Value: [0]


The result above (0) tells us the players will not be getting extra credits.

Naive Bayes using multiple labels

In [ ]:
#import scikit-learn dataset library
from sklearn import datasets

#load dataset
diabetes=datasets.load_diabetes()

In [ ]:
df=pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.columns= ['preg', 'gluc', 'BloodP', 'SkinT', 'Insul', 'BMI', 'DiabetesPed', 'Age', 'Outcome']
df.head()

preg  gluc  BloodP  SkinT  Insul   BMI  DiabetesPed  Age  Outcome
0     6   148      72     35      0  33.6        0.627   50        1
1     1    85      66     29      0  26.6        0.351   31        0
2     8   183      64      0      0  23.3        0.672   32        1
3     1    89      66     23     94  28.1        0.167   21        0
4     0   137      40     35    168  43.1        2.288   33        1

In [ ]:
x_data = df[['preg', 'gluc', 'BloodP', 'SkinT', 'Insul', 'BMI', 'DiabetesPed', 'Age', 'Outcome']]
y_data = df['Outcome']

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3,random_state=109) # 70% training and 30% test

In [ ]:
# model generation
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

#Train the model using the training sets
model.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

#This is to evaluate the model
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 1.0
